name: Plugin-test
description: Exceptional functionality
author: https://github.com/lizrabuya
requirements:
  - bash
  - docker
configuration:
  properties:
    propagate-env-vars:
      type: boolean
  additionalProperties: false
